[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
uuid = { git = "https://github.com/mesalock-linux/uuid-sgx.git", features = ["v5"] }
#protected_fs_rs = { git = "https://github.com/mesalock-linux/protected_fs_rs" }

#[dependencies.rusty-leveldb]
#git = "https://github.com/automata-network/rusty_leveldb_sgx.git"
#path = "../../../../rusty_leveldb_sgx"

#[dependencies.sled]
#default-features = false
#features = ["mesalock_sgx"]
#path = "../../../../sled-sgx"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["backtrace", "untrusted_fs"] }
#sgx_tcrypto = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
#sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
#sgx_tseal = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
#sgx_serialize = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
#sgx_alloc = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
#sgx_libc = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
